spring.application.name=jobms
server.port=8082


# ===============================
# = H2 DATABASE CONFIG
# ===============================
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# ===============================
# = PostgreSQL DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/job
spring.datasource.username=jobuser
spring.datasource.password=jobpassword
# ===============================
# = JPA / HIBERNATE CONFIG
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database=POSTGRESQL

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

#Eureka

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Zipkin 
#1.0 means everything will be traced in production it may slow down system, so we can use 2.5 or anything suitable
management.tracing.sampling.probability=1.0 
